node export-nghiem-thu-de-tai-animal "$@"
node export-nghiem-thu-de-tai-mycology "$@"
node export-nghiem-thu-de-tai-soil "$@"
node export-nghiem-thu-de-tai-vegetable "$@"
node export-nghiem-thu-de-tai-geological "$@"
node export-nghiem-thu-de-tai-paleontological "$@"